import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { firebaseConfig } from '../firebase-public-config.js';
export async function buildWorker({ test = false, write = true } = {}) {
  return build({ entryPoints: [fileURLToPath(new URL('../push-worker/service-worker.js', import.meta.url))], bundle: true, format: 'iife', target: ['chrome100'], minify: true, legalComments: 'inline', write,
    outfile: fileURLToPath(new URL('../firebase-messaging-sw.js', import.meta.url)),
    define: { __FIREBASE_CONFIG__: JSON.stringify(test ? { projectId: 'demo-silverforge', apiKey: 'demo-key', appId: 'demo-app', messagingSenderId: '1234567890' } : firebaseConfig) },
    banner: { js: '// Generated by npm run build:worker from Firebase Web SDK 12.16.0. Edit push-worker/service-worker.js.' } });
}
if (process.argv[1] === fileURLToPath(import.meta.url)) { await buildWorker(); console.log('PASS Bundled Firebase 12.16.0 messaging service worker.'); }
